### ISSUE TITLE
An example

### ISSUE THREAD

**Issue by arcbtc** [JASchilz/pystrike#1]
I'm struggling a little with the readme, is it worth putting an example after:

> For example, if you are waiting on payment for a charge, you might run charge.update() and then access charge.paid to see if a payment has been recorded for the charge on the Strike server.

**Comment by JASchilz** [comment]
Sure. I hope that clarifies it! I added a more verbose example that includes polling the server with `charge.update()` and retrieving `charge.paid`, and I explained a bit more down in the `Updating a Charge` section.

**Comment by arcbtc** [comment]
Wow, it really is that simple! I was overthinking it. Brilliant work this library, thanks a lot

**Comment by JASchilz** [comment]
Thanks and cheers. (:
